"""add_plan_share_and_collaborators

Revision ID: 9c1101f73e68
Revises: 8066c01fd64b
Create Date: 2026-09-03 01:54:00.518825

[Gate #25] SharePage.tsx/inviteCollaborator等が前提としていた共有リンク・
コラボレーター機能のテーブルが一切存在しなかったため新規追加。
plan_share_links・plan_collaboratorsの2テーブルを新規作成するのみで、
既存テーブルへのALTER/DROPは一切行わない(追加のみの安全なマイグレーション)。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1101f73e68'
down_revision: Union[str, Sequence[str], None] = '8066c01fd64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_collaborators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invite_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['travel_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_collaborators_id'), 'plan_collaborators', ['id'], unique=False)
    op.create_table('plan_share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['travel_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_share_links_id'), 'plan_share_links', ['id'], unique=False)
    op.create_index(op.f('ix_plan_share_links_token'), 'plan_share_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_share_links_token'), table_name='plan_share_links')
    op.drop_index(op.f('ix_plan_share_links_id'), table_name='plan_share_links')
    op.drop_table('plan_share_links')
    op.drop_index(op.f('ix_plan_collaborators_id'), table_name='plan_collaborators')
    op.drop_table('plan_collaborators')
    # ### end Alembic commands ###
