"""Add missing columns and tables

Revision ID: ca63a9e8d7de
Revises: 18201c72e72c
Create Date: 2025-08-04 01:45:12.367045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca63a9e8d7de'
down_revision: Union[str, Sequence[str], None] = '18201c72e72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('itinerary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_plans_id'), 'travel_plans', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.add_column('optimization_results', sa.Column('optimization_type', sa.String(), nullable=True))
    op.add_column('optimization_results', sa.Column('original_data', sa.JSON(), nullable=True))
    op.add_column('optimization_results', sa.Column('optimized_data', sa.JSON(), nullable=True))
    op.add_column('optimization_results', sa.Column('improvement_metrics', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('optimization_results_user_id_fkey'), 'optimization_results', type_='foreignkey')
    op.drop_column('optimization_results', 'user_id')
    op.drop_column('optimization_results', 'parameters')
    op.drop_column('optimization_results', 'original_route')
    op.drop_column('optimization_results', 'cost_saved')
    op.drop_column('optimization_results', 'distance_saved')
    op.drop_column('optimization_results', 'algorithm_used')
    op.drop_column('optimization_results', 'optimized_route')
    op.drop_column('optimization_results', 'optimization_score')
    op.drop_column('optimization_results', 'time_saved')
    op.drop_column('optimization_results', 'computation_time')
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.add_column('optimization_results', sa.Column('computation_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('time_saved', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('optimization_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('optimized_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('algorithm_used', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('distance_saved', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('cost_saved', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('original_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('optimization_results', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('optimization_results_user_id_fkey'), 'optimization_results', 'users', ['user_id'], ['id'])
    op.drop_column('optimization_results', 'improvement_metrics')
    op.drop_column('optimization_results', 'optimized_data')
    op.drop_column('optimization_results', 'original_data')
    op.drop_column('optimization_results', 'optimization_type')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_travel_plans_id'), table_name='travel_plans')
    op.drop_table('travel_plans')
    # ### end Alembic commands ###
